---
title: Quick Subset Using data.table
author: Guanghua Wang
date: '2017-07-03'
slug: quick-subset-data-table
categories: ["R Learning Notes"]
tags: ["R data.table"]
summary: "In terms of speed, `,I` in `data.table` is the fastest."
---

```{r setup}
if (!require(data.table)) install.packages("data.table")
library(dplyr)
library(tidyr)
library(data.table)
data(population, package = "tidyr")
```

I use `population` data from `tidyr` package as an example.

```{r data description}
glimpse(population)
summary(population)
class(population)
populationDT <- as.data.table(population)
class(populationDT)
```

## The .SD Method in `data.table`
```{r SD methond in data.table}
t <- proc.time()
tmp1 <- populationDT[
  , .SD[population < median(population)], by = c("country")
]
proc.time() - t
```

## The .I Methond in `data.table`
```{r I methond in data.table}
t <- proc.time()
tmp2 <- populationDT[
  populationDT[, .I[population < median(population)], by = c("country")]$V1
]
proc.time() - t
```

## The `dplyr` method
```{r dployr methond}
t <- proc.time()
tmp3 <- population %>% 
  group_by(country) %>% 
  filter(population < median(population)) %>% 
  ungroup()
proc.time() - t
```

## Whether Is the Fianl Data Identical?
```{r compare data}
identical(tmp1, tmp2)
setdiff(tmp2, tmp3)
```

I got same data.frame by three different methods. In terms of speed, `,I` in `data.table` is the fastest.